name: "Install Verible"
description: "Install Verible release"

inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    default: ''
  verible_version:
    description: 'Use selected Verible version (defaults to latest release)'
    default: 'latest'

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      shell: bash
      run: |
          sudo apt install -y curl jq wget
    - name: Download and unpack Verible
      shell: bash
      run: |
          mkdir verible
          if [ "${{ inputs.verible_version }}" = "latest" ]; then
            VERIBLE_RELEASES_JSON=$(curl --header 'authorization: Bearer ${{ inputs.github_token }}' -fsSL https://api.github.com/repos/chipsalliance/verible/releases/latest)
            VERIBLE_TARBALL=$(echo $VERIBLE_RELEASES_JSON | jq -r '.assets[] | select(.browser_download_url | test("(?=.*linux-static)(?=.*x86_64)")).browser_download_url')
          else
            VERIBLE_TARBALL="https://github.com/chipsalliance/verible/releases/download/${{ inputs.verible_version }}/verible-${{ inputs.verible_version }}-linux-static-x86_64.tar.gz"
          fi
          echo "Downloading $VERIBLE_TARBALL"
          wget -qO- $VERIBLE_TARBALL | tar -zxvf - -C verible --strip-components=1
          for i in ./verible/bin/*; do sudo cp $i /usr/local/bin/$(basename $i); done
